steps:
  # Install root dependencies using Node 20
  - name: 'node:20'
    entrypoint: npm
    args: ['ci']
    id: Install dependencies
    timeout: 600s

  # Install frontend packages and Vite
  - name: 'node:20'
    entrypoint: npm
    args: ['install', '--prefix', 'frontend']
    id: Install frontend packages
    timeout: 600s

  # Validate required tooling
  - name: node:20
    entrypoint: bash
    args:
      - -c
      - |
          if ! command -v vite >/dev/null 2>&1; then
            echo "\u274c vite is not installed. Run 'npm install -D vite' and try again."
            exit 1
          fi
          if ! command -v firebase >/dev/null 2>&1; then
            echo "\u274c firebase-tools is not installed. Add it to your devDependencies or install globally."
            exit 1
          fi
    id: Validate tooling

  # Fail early if required env vars aren't set
  - name: node:20
    entrypoint: bash
    args:
      - -c
      - |
          if [ -z "$FIREBASE_TOKEN" ] || [ -z "$PROJECT_ID" ]; then
            echo "\u274c FIREBASE_TOKEN or PROJECT_ID not provided."
            exit 1
          fi
    id: Check env

  # Build the frontend with Vite via root script
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    id: Build frontend
    timeout: 600s

  # Deploy Firebase functions
  - name: 'node:20'
    entrypoint: bash
    args:
      - -c
      - |
          npm install -g firebase-tools
          if firebase deploy --only functions --token "$FIREBASE_TOKEN" --project "$PROJECT_ID"; then
            echo "\u2705 Functions deployed"
          else
            echo "\u274c Functions deployment failed"
            exit 1
          fi
    id: Deploy functions
    timeout: 1200s

  # Deploy Cloud Run service from container image (no Buildpacks)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
          if gcloud run deploy "${_SERVICE_NAME}" --image=gcr.io/$PROJECT_ID/${_SERVICE_NAME} --region=${_REGION}; then
            echo "\u2705 Cloud Run service deployed"
          else
            echo "\u274c Cloud Run deployment failed"
            exit 1
          fi
    id: Deploy service

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/firebase-ci-token/versions/latest
      env: FIREBASE_TOKEN
logsBucket: "${_LOGS_BUCKET}"
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _LOGS_BUCKET: ""
  _SERVICE_NAME: ""
  _REGION: ""
