steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']
    id: Install backend
    timeout: 600s

  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'functions'
    id: Install functions
    timeout: 600s

  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'frontend'
    id: Install frontend
    timeout: 600s

  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    id: Install test deps
    timeout: 300s

  - name: 'gcr.io/cloud-builders/npm'
    args: ['test', '--silent']
    id: Run tests
    timeout: 600s

  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '--prefix', 'frontend']
    id: Install frontend build deps
    timeout: 600s

  - name: 'gcr.io/cloud-builders/npm'
    args: ['--prefix', 'frontend', 'run', 'build']
    id: Build frontend
    timeout: 600s

  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: bash
    args:
      - -c
      - |
          npm install -g firebase-tools
          firebase deploy --only functions --token "$FIREBASE_TOKEN" --project "$PROJECT_ID"
    id: Deploy functions
    timeout: 1200s

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'super-intelligence', '--source=.', '--region=europe-west1']
    id: Deploy service

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/firebase-ci-token/versions/latest
      env: FIREBASE_TOKEN
