steps:
  # Install root dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']
    id: Install dependencies
    timeout: 600s

  # Install frontend packages
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '--prefix', 'frontend']
    id: Install frontend packages
    timeout: 600s

  # Build the frontend (runs `vite build` via root script)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    id: Build frontend
    timeout: 600s

  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: bash
    args:
      - -c
      - |
          npm install -g firebase-tools
          firebase deploy --only functions --token "$FIREBASE_TOKEN" --project "$PROJECT_ID"
    id: Deploy functions
    timeout: 1200s

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'super-intelligence', '--source=.', '--region=europe-west1']
    id: Deploy service

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/firebase-ci-token/versions/latest
      env: FIREBASE_TOKEN
