name: Cloud Run Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      SERVICE_NAME: node-backend
    steps:
      - uses: actions/checkout@v3
      - name: Verify functions package.json
        run: |
          test -f functions/package.json || { echo "\u274c Missing package.json"; exit 1; }
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Configure npm registry
        working-directory: functions
        run: echo "registry=https://registry.npmjs.org/" > .npmrc
      - name: Clear deprecated npm proxy config
        working-directory: functions
        run: |
          npm config delete http-proxy || true
          npm config delete https-proxy || true
          sed -i '/http-proxy/d;/https-proxy/d' .npmrc || true
      - name: Install dependencies
        run: npm --prefix functions install
      - name: Build functions
        run: npm --prefix functions run build
      - name: Run tests
        working-directory: functions
        run: npm test
      - name: Verify start script
        run: timeout 3 npm --prefix functions start || true
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Build container image
        run: gcloud builds submit functions --tag gcr.io/$PROJECT_ID/$SERVICE_NAME --project $PROJECT_ID
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME \
            --region us-central1 \
            --platform managed \
            --project $PROJECT_ID \
            --allow-unauthenticated
