name: Firebase CI/CD

on:
  push:
    branches: [main]

jobs:
  binary-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Detect binary files
        run: |
          git diff --cached --name-only | xargs file | grep -v 'text' && exit 1 || echo "No binaries"

  deploy:
    needs: binary-check
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
          npm --prefix functions install
          npm run sync-agents
          npm run validate-metadata

      - name: Validate agent metadata
        run: node scripts/validateAgentMetadata.js

      - name: Lint and test
        run: |
          npm run lint --if-present
          npm --prefix functions test --silent

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only functions,hosting,firestore --project ${{ secrets.FIREBASE_PROJECT_ID }}
