name: Firebase Dev Deploy

on:
  push:
    tags:
      - v1.0-mvp

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - name: Load FIREBASE_TOKEN
        run: |
          if [ -z "$FIREBASE_TOKEN" ] && [ -f ../.env ] && [ ! -f .env ]; then
            cp ../.env .env
          fi
          if [ -z "$FIREBASE_TOKEN" ] && [ -f .env ]; then
            token=$(grep -E '^FIREBASE_TOKEN=' .env | cut -d '=' -f2- | tr -d '"')
            if [ -n "$token" ]; then
              echo "FIREBASE_TOKEN=$token" >> "$GITHUB_ENV"
              echo "Loaded FIREBASE_TOKEN from .env"
            else
              echo "::warning::FIREBASE_TOKEN not found in .env"
            fi
          elif [ -z "$FIREBASE_TOKEN" ]; then
            echo "::warning::FIREBASE_TOKEN not set"
          fi
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy to Firebase
        run: |
          if [ -z "$FIREBASE_TOKEN" ]; then
            echo "::warning::FIREBASE_TOKEN not set - skipping deploy"
            exit 0
          fi
          firebase deploy --token "$FIREBASE_TOKEN"
