name: AJV Lock

on:
  push:
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'scripts/checkDevDeps.js'
      - '.github/workflows/main.yml'
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'scripts/checkDevDeps.js'
      - '.github/workflows/main.yml'

jobs:
  cold-install-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Remove node_modules
        run: rm -rf node_modules
      - name: Install dependencies
        run: npm ci
      - name: Verify dev dependencies
        run: node scripts/checkDevDeps.js
